#!/bin/bash
yum update -y
cd /home/ec2-user
wget https://github.com/albuild/snap/releases/download/v0.1.0/snap-confine-2.36.3-0.amzn2.x86_64.rpm
wget https://github.com/albuild/snap/releases/download/v0.1.0/snapd-2.36.3-0.amzn2.x86_64.rpm
yum -y install snap-confine-2.36.3-0.amzn2.x86_64.rpm snapd-2.36.3-0.amzn2.x86_64.rpm
systemctl enable --now snapd.socket
systemctl restart snapd.seeded.service
snap install get-iplayer
export PATH="$PATH:/snap/bin"
